[package]
name = "sdl2-gallery"
version = "0.1.0"
authors = ["Amadeus <gliheng@gmail.com>"]

[dependencies]
stdweb = "0.3.0"

[dependencies.sdl2]
version = "0.31.0"
default-features = false
features = ["image", "unsafe_textures"]
