[package]
name = "rust_loader"
version = "0.1.0"
authors = ["Amadeus <gliheng@gmail.com>"]

[dependencies]
stdweb = "0.4.2"
num = "0.1.42"

[dependencies.sdl2]
version = "0.31.0"
default-features = false
features = ["image", "unsafe_textures"]
